plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

version = project.mod_version
group = project.maven_group
base { archivesName = project.archives_base_name }

repositories {
    maven { url = 'https://repo.hypixel.net/repository/Hypixel/' }
    maven { url = 'https://maven.terraformersmc.com/releases/' }
}

dependencies {
    compileOnly "net.hypixel:mod-api:1.0.1"
    compileOnly("com.terraformersmc:modmenu:18.0.0") { transitive = false }
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
    inputs.property "version", project.version
    inputs.property "commit", (System.getenv("GITHUB_SHA") ?: "dev")
    filesMatching("fabric.mod.json") { expand "version": inputs.properties.version }
    filesMatching("farmprofit-build.txt") { expand "commit": inputs.properties.commit }
}

tasks.withType(JavaCompile).configureEach { it.options.release = 25 }

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}
